[[items]]
date = "Service"
title = "Reviewer"
content = "Reviewer for TPAMI, TCSVT, KBS, ICML, NeurIPS, AAAI, ICMR, and ICME."

[[items]]
date = "2024"
title = "ECCV Challenge"
content = "Winner Solution Award in the Corner Case Scene Understanding track at the ECCV 2024 Autonomous Driving Challenge."

[[items]]
date = "2024"
title = "CVPR Challenge"
content = "Innovation Award in the Driving with Language track at the CVPR 2024 Autonomous Driving Challenge."

[[items]]
date = "2024"
title = "Thesis Award"
content = "Outstanding Master's Thesis Award of Chongqing."

[[items]]
date = "Award"
title = "Student Presentation"
content = "Outstanding Student Presentation Award at the Frontier Forum on Multi-Granularity Cognitive Computing."
